INSERT INTO USER_TYPES VALUES(1,'EMPLOYEE');
INSERT INTO USER_TYPES VALUES(2,'AFFILIATE');
INSERT INTO USER_TYPES VALUES(3,'CUSTOMER');


INSERT INTO USERS VALUES(1,'RAJ',CURRENT_DATE(),1);
INSERT INTO USERS VALUES(2,'KANAGARAJ',CURRENT_DATE(),2);
INSERT INTO USERS VALUES(3,'JOHN',CURRENT_DATE()-1000,3);
INSERT INTO USERS VALUES(4,'JOE',CURRENT_DATE(),2);
INSERT INTO USERS VALUES(5,'MOHAN',CURRENT_DATE(),1);
INSERT INTO USERS VALUES(6,'MOHAMMAD',CURRENT_DATE()-100,3);

INSERT INTO PRODUCT_TYPES VALUES(1,'GROCERIES');
INSERT INTO PRODUCT_TYPES VALUES(2,'OTHER');


INSERT INTO PRODUCTS VALUES(1,'Apple',10.00,2);
INSERT INTO PRODUCTS VALUES(2,'Beans',15.00,1);
INSERT INTO PRODUCTS VALUES(3,'Ladies Finger',17.00,1);
INSERT INTO PRODUCTS VALUES(4,'Orange',19.00,2);
INSERT INTO PRODUCTS VALUES(5,'Carrot',90.00,1);
INSERT INTO PRODUCTS VALUES(6,'TV',75.00,2);
INSERT INTO PRODUCTS VALUES(7,'Locker',56.00,2);
INSERT INTO PRODUCTS VALUES(8,'Leaf',20.00,1);
INSERT INTO PRODUCTS VALUES(9,'Mixer',30.00,2);